# Generated by Django 4.0.1 on 2022-01-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardenapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vegetable',
            old_name='vdescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='zone',
            old_name='zdescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='zone',
            old_name='vintro',
            new_name='intro',
        ),
    ]
