# Generated by Django 4.0.1 on 2022-01-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenapp', '0002_rename_vdescription_vegetable_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable',
            name='description',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='tips',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='zone',
            name='description',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='zone',
            name='intro',
            field=models.CharField(max_length=800),
        ),
    ]
